### ISSUE TITLE
files appear to be missing

### ISSUE THREAD

**Issue by PatSammon** [Glorf/recipenlg#5]
Hello,
I was looking at the generation folder, and according to the README.md there should be a "train.sh". "play.sh" and "credentials.sh" file. I am not seeing those files at all in this directory.

**Comment by Glorf** [comment]
These were just the execution scripts used for running training and/or providing user credentials to dump trained models directly to s3. You should be generally safe to train without them.
Since huggingface transformers library evolves very fast, you should consider using their new scripts (which are getting better and better in general) to train the model yourself: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py
